### ISSUE TITLE
Main config

### ISSUE THREAD

**Issue by kinggoesgaming** [Radical-Delta/MinersHandouts#1]
First off, I hate the plain standard `<pluginid>`.conf and config.conf names for configs. There are also likely more than 1 config possible. Therefore I think the more appropriate name for the main config would be global.conf. This will include(and not limited to):

``` yml
verbose: if a short error message or entire stack is printed. The stack is still printed for critical errors.
save: how often configs are saved to disk
sql credentials
```

Those are required. Any other suggested config options are welcome.

----
After further discussions the new config nodes are

``` hocon
api {
    url = "localhost/API"
    password = "passwd"
}
save = 300
verbose = false
